id: P006779
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8060
  title: མ་ཧཱ་གུ་རུ། མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ། བཻ་རོ་ཙ་ན། རྗེ་བཙུན་མི་ལ་བཅས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    1240f704dc6742a9961b96a90e9fcc96:
      image_group_id: I1PD96630
      title: ''
      volume_number: 1
      total_pages: 334
